version: '3'

services:
  basic_service:
    image: wcschlosser/basic-service:0.1.0
    ports:
    - "9000:8080"
    deploy:
      replicas: 4
      placement:
        constraints:
        - node.role == worker
  log_ip_service:
    image: wcschlosser/log-ip-service:0.1.0
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.role == manager
